### PR TITLE
357: fixed signout design and behaviors

### LINKED ISSUE #357: Sign-out button not clear on Desktop
1) c'est pas clair où on sign out (icon non visible avant hover/mouseenter) , donc faut rajouter le bouton a coté de ton nom sur le desktop (comme la version tablet)
2) y'a une boucle infini qqpart (cf la vidéo)

### PR DESCRIPTION
**Pull request by cy-len**
Improved design of signout and simplified SignOut.tsx. Also added scroll behavior to the SidePanel.tsx for short viewport sizes

Fixes #357 : https://github.com/globalbuildingdatainitiative/web-app/issues/357

### CODE REVIEW

File: src/components/SignOut/SignOut.tsx [hunk 1]
```diff
@@ -24,36 +23,31 @@ export const SignOut = ({ collapsed }: SignOutProps) => {
...
+      {!collapsed && (
+        <Text
+          style={{
+            whiteSpace: 'normal',
+            marginBottom: 8
+          }}
+        >
+          <div>{user?.firstName || '(No first name)'} {user?.lastName || '(No last name)'}</div>
+          <div style={{ fontSize: 14, lineHeight: 1.25 }}>{user?.email || '(No email)'}</div>
+          <div style={{ fontSize: 14, lineHeight: 1.25 }}>{user?.organization?.name || 'No organization'}</div>
```
[the remark this answers is not in the document]
Comment (guilbep) [reply src/components/SignOut/SignOut.tsx:36]: Nope, It's okay, 2 repeat does not need refactoring and extracting

File: src/components/SignOut/SignOut.tsx [hunk 2]
```diff
@@ -24,36 +23,31 @@ export const SignOut = ({ collapsed }: SignOutProps) => {
   }
 
   return (
-    <>
+    <div>
```
Comment (guilbep) [inline src/components/SignOut/SignOut.tsx:26]: @cy-len  Doesn't it add a level of complexity/ Dom depth level to use div instead of React Fragment? Why do you do that??

File: src/components/SidePanel/SidePanel.tsx [hunk 3]
```diff
@@ -151,15 +152,7 @@ export const SidePanel = ({ collapsed, toggleCollapsed }: SidePanelProps) => {
...
-      <AppShell.Section
-        style={{
-          display: 'flex',
-          justifyContent: 'center',
-          alignItems: 'center',
-          marginTop: 'auto',
-          marginBottom: '20px',
-        }}
-      >
+      <AppShell.Section>
```
Comment (guilbep) [inline src/components/SidePanel/SidePanel.tsx:155]: @cy-len What happened to the style ?

**Review by guilbep — CHANGES_REQUESTED** [review]

File: src/components/SidePanel/SidePanel.tsx (hunk 3 above)
Comment (cy-len) [reply src/components/SidePanel/SidePanel.tsx:155]: It was just centering the button which looked very weird. without it the button is aligned with the other links of the panel

File: src/components/SignOut/SignOut.tsx [hunk 4]
```diff
@@ -24,36 +23,31 @@ export const SignOut = ({ collapsed }: SignOutProps) => {
...
-            style={{
-              whiteSpace: 'normal',
-              width: '200px',
-            }}
-          >
-            {user?.firstName || 'Nobody'} from {user?.organization?.name || 'Unknown'}
-          </Text>
-        )}
+        <IconLogout size={20} />
+        {!collapsed && <Text style={{ marginLeft: 8 }}>Sign Out</Text>}
```
[the remark this answers is not in the document]
Comment (cy-len) [reply src/components/SignOut/SignOut.tsx:49]: with great pleasure
